plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.vpnauto'
    compileSdk 34

    defaultConfig {
        applicationId 'dev.vpnauto'
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName '0.2.0-m1'
    }
}

dependencies {
    // On-device OCR for reading the TOTP code off the Authenticator screen.
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
